# Generated by Django 3.0.6 on 2020-06-09 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intranet_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('permission', models.CharField(default='placeur', max_length=50)),
                ('is_manager', models.BooleanField(default=False)),
                ('city', models.CharField(default='Neuchatel', max_length=50)),
                ('infos', models.CharField(default='nothing', max_length=150)),
                ('holidays', models.CharField(default='nothing', max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='template', max_length=50)),
                ('columns', jsonfield.fields.JSONField(default='[\n  "Date",\n  "Vacance Scolaire",\n  "Evenement",\n  "Appolo",\n  "Arcade",\n  "Bio",\n  "Rex",\n  "Studio"\n]')),
                ('content', jsonfield.fields.JSONField(default='[\n    [\n        "lundi 01",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "mardi 02",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "mercredi 03",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "jeudi 04",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "vendredi 05",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "samedi 06",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "dimanche 07",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "lundi 08",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "mardi 09",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "mercredi 10",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "jeudi 11",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "vendredi 12",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "samedi 13",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "dimanche 14",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "lundi 15",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "mardi 16",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "mercredi 17",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "jeudi 18",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "vendredi 19",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "samedi 20",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "dimanche 21",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "lundi 22",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "mardi 23",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "mercredi 24",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "jeudi 25",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "vendredi 26",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "samedi 27",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "dimanche 28",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ]\n]')),
                ('id_create', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('specific_content', jsonfield.fields.JSONField(null=True)),
                ('id_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranetapp.Template')),
            ],
        ),
    ]
