# Generated by Django 3.0.6 on 2020-06-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='month',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='specific_content',
        ),
        migrations.AddField(
            model_name='calendar',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='content',
            field=models.TextField(default="[{'Date':'hello', 'Vacance Scolaire':'haha'}]"),
        ),
    ]
