# Generated by Django 3.0.6 on 2020-05-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0002_auto_20200518_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='infos',
            field=models.CharField(default='nothing', max_length=150),
        ),
    ]
