# Generated by Django 3.0.6 on 2020-06-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0003_auto_20200604_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='id_Template',
            new_name='id_template',
        ),
    ]
