# Generated by Django 3.0.6 on 2020-06-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0003_auto_20200615_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='content',
            new_name='template_content',
        ),
    ]
