# Generated by Django 3.0.6 on 2020-05-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0004_calendar_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='month',
            field=models.CharField(default='mois', max_length=50),
        ),
    ]
