# Generated by Django 3.0.6 on 2020-05-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0005_calendar_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='holidays',
            field=models.CharField(default='nothing', max_length=150),
        ),
    ]
