# Generated by Django 3.0.6 on 2020-06-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0006_auto_20200618_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='date',
            field=models.TextField(),
        ),
    ]
