# Generated by Django 3.0.6 on 2020-06-08 09:53

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0008_auto_20200608_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='columns',
            field=jsonfield.fields.JSONField(default='[\n  "Date",\n  "Vacance Scolaire",\n  "Evenement",\n  "Appolo",\n  "Arcade",\n  "Bio",\n  "Rex",\n  "Studio"\n]'),
        ),
        migrations.AlterField(
            model_name='template',
            name='content',
            field=jsonfield.fields.JSONField(default='[\n    [\n        "lundi 01",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "mardi 02",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "mercredi 03",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "jeudi 04",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "vendredi 05",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "samedi 06",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "dimanche 07",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "lundi 08",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "mardi 09",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "mercredi 10",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "jeudi 11",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "vendredi 12",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "samedi 13",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "dimanche 14",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "lundi 15",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "mardi 16",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "mercredi 17",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "jeudi 18",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "vendredi 19",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "samedi 20",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "dimanche 21",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "lundi 22",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "mardi 23",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "mercredi 24",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "jeudi 25",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "vendredi 26",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "samedi 27",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ],\n    [\n        "dimanche 28",\n        "",\n        "",\n        "",\n        "",\n        "",\n        "",\n        ""\n    ]\n]'),
        ),
    ]
