# Generated by Django 3.0.6 on 2020-07-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0013_schedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='ScheduleCinema',
        ),
    ]
