# Generated by Django 3.0.6 on 2020-07-07 09:11

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0014_auto_20200706_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulecinema',
            name='content',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
