# Generated by Django 3.0.6 on 2020-07-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0015_auto_20200707_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulecinema',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
