# Generated by Django 3.0.8 on 2020-07-13 09:16

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0016_auto_20200707_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='specific_content',
            field=jsonfield.fields.JSONField(),
        ),
    ]
