# Generated by Django 3.0.8 on 2020-07-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0018_auto_20200713_0947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calendar',
            new_name='Planning',
        ),
    ]
