# Generated by Django 3.0.8 on 2020-07-15 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0022_auto_20200714_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intranet_user',
            name='is_active',
        ),
    ]
