# Generated by Django 3.0.8 on 2020-07-15 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0023_remove_intranet_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planning',
            old_name='id_creator',
            new_name='id_create',
        ),
        migrations.AddField(
            model_name='information',
            name='id_create',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
